# Generated by Django 2.2.5 on 2019-09-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageversion',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
