# Generated by Django 2.2.5 on 2019-09-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_auto_20190922_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='status',
            field=models.CharField(choices=[('err', 'Error'), ('inv', 'Invalid Upload'), ('rdy', 'Ready'), ('prs', 'Processing'), ('wtp', 'Waiting to process'), ('wtu', 'Waiting to upload')], default='wtu', max_length=3),
        ),
    ]
