# Generated by Django 2.2.5 on 2019-09-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20190922_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imageversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
